features = [
            'self_size',
            'self_resolution',
            'self_instances',
            'self_is_network',
            'other_pictures',
            'other_textviews',
            'other_buttons',
            'social_image',
            'multimedia_image',
            'information_image',
            'social_transition',
            'multimedia_transition',
            'information_transition',
            'other_sizes',
            'other_resolutions',
            'other_media_network',
            'other_media_database',
            'adjacent_textvew',
            'adjacent_textview_size',
            'ratio_large_textviews',
            'animation_removed',
            'animation_removed_transition',
            'animation_removed_static',
            'animation_removed_image_size',
            'animation_run_time',
            'image_reduction_score',
            'is_removed',
            'self_size_a',
            'self_resolution_a',
            'self_instances_a',
            'self_is_network_a',
            'other_pictures_a',
            'other_textviews_a',
            'other_buttons_a',
            'social_a',
            'multimedia_a',
            'information_a',
            'other_sizes_a',
            'other_resolutions_a',
            'other_media_network_a',
            'other_media_database_a',
            'adjacent_textvew_a',
            'adjacent_textview_size_a',
            'ratio_large_textviews_a'
            'is_removed_a'
            ]

correct_versions = {
                    'A1a': 'V1',
                    'A1b': 'V0',
                    'A2a': 'V5',
                    'A2b': 'V5',
                    'A3a': 'V1',
                    'A3b': 'V0',
                    'A3c': 'V1',
                    'A3d': 'V3',
                    'A4a': 'V0',
                    'A4b': 'V3',
                    'A4c': 'V1',
                    'A4d': 'V1',
                    'A4f': 'V3',
                    'A5a': 'V1',
                    'A6a': 'V1',
                    'A7a': 'V5',
                    'A7b': 'V4',
                    'A8a': 'V0',
                    'A9a': 'V5',
                    'A10a': 'V5',
                    'A11a': 'V3',
                    'A12a': 'V1',
                    'A12b': 'V1',
                    'A13a': 'V1',
                    'A14a': 'V1',
                    'A14b': 'V4',
                    'A15a': 'V5',
                    'A15b': 'V5',
                    'A16a': 'V1',
                    'A16b': 'V5'
                    }

